name: Github Pages

on:
  push:
    branches:
      - develop   # Branche de développement
      - test      # Branche de test
      - main      # Branche de production

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set safe directory for Git
        run: git config --global --add safe.directory /github/workspace

      # Utilisation du cache pour les dépendances
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      # Définir la configuration en fonction de la branche (prod, test, dev)
      - name: Set environment variables
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            echo "JEKYLL_ENV=production" >> $GITHUB_ENV
            echo "CNAME=blog.azy.solutions" >> $GITHUB_ENV
            echo "JEKYLL_CONFIG=_config.yml,_config_prod.yml" >> $GITHUB_ENV
          elif [ "${{ github.ref }}" == "refs/heads/test" ]; then
            echo "JEKYLL_ENV=test" >> $GITHUB_ENV
            echo "CNAME=test.blog.azy.solutions" >> $GITHUB_ENV
            echo "JEKYLL_CONFIG=_config.yml,_config_test.yml" >> $GITHUB_ENV
          else
            echo "JEKYLL_ENV=development" >> $GITHUB_ENV
            echo "CNAME=dev.blog.azy.solutions" >> $GITHUB_ENV
            echo "JEKYLL_CONFIG=_config.yml,_config_dev.yml" >> $GITHUB_ENV
          fi

      # Déploiement avec la configuration appropriée
      - uses: jeffreytse/jekyll-deploy-action@v0.6.0
        with:
          provider: 'github'
          token: ${{ secrets.GITHUB_TOKEN }}  # Utilise ton Personal Access Token (PAT)
          repository: ''                      # Par défaut, le dépôt actuel
          branch:  ${{ env.DEPLOY_BRANCH }}   # Branche de déploiement, ici gh-pages
          jekyll_src: './'                    # Répertoire racine du projet Jekyll
          jekyll_cfg: ${{ env.JEKYLL_CONFIG }}  # Utilisation du fichier de config en fonction de l'environnement
          cname: ${{ env.CNAME }}              # CNAME selon l'environnement
          actor: ''                           # Par défaut, l'acteur est GITHUB_ACTOR
